# Generated by Django 3.1.2 on 2020-10-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=50, verbose_name='职位名称')),
                ('salary', models.CharField(max_length=50, verbose_name='薪资')),
            ],
            options={
                'verbose_name': '招聘信息',
                'verbose_name_plural': '招聘信息',
            },
        ),
    ]
