# Generated by Django 3.1.2 on 2020-10-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='', max_length=100, verbose_name='企业名称'),
        ),
    ]
