# Generated by Django 3.1.2 on 2020-10-30 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='user',
            field=models.OneToOneField(default='', help_text="选择/添加用户类型为'student'的账户", limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='user',
            field=models.OneToOneField(default='', help_text="选择/添加用户类型为'teacher'的账户", limit_choices_to={'user_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='姓名'),
        ),
    ]
