# Generated by Django 3.1.2 on 2020-10-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('man', '男'), ('female', '女')], default='man', max_length=10, verbose_name='性别')),
                ('major', models.CharField(default='软件工程', max_length=30, verbose_name='专业')),
            ],
            options={
                'verbose_name': '毕业生',
                'verbose_name_plural': '毕业生',
            },
        ),
    ]
