# Generated by Django 3.1.2 on 2020-10-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '企业信息',
                'verbose_name_plural': '企业信息',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='', max_length=100, verbose_name='企业名称')),
                ('position_name', models.CharField(max_length=50, verbose_name='职位名称')),
                ('salary', models.CharField(max_length=50, verbose_name='薪资')),
                ('detail', models.TextField(default='', verbose_name='职位详情')),
            ],
            options={
                'verbose_name': '岗位信息',
                'verbose_name_plural': '岗位信息',
            },
        ),
    ]
