# Generated by Django 3.1.2 on 2020-11-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_enterprises_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='company',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='position_name',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='salary',
        ),
        migrations.AddField(
            model_name='jobs',
            name='company_name',
            field=models.CharField(default='', help_text='管理员可以发布任意企业的岗位信息，即使未在此系统注册', max_length=100, verbose_name='企业名称'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='company_size',
            field=models.CharField(default='', max_length=20, verbose_name='企业大小'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='company_type',
            field=models.CharField(default='民营公司', max_length=10, verbose_name='企业类型'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='education',
            field=models.CharField(default='', max_length=10, verbose_name='学历'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='max_salary',
            field=models.FloatField(default=0, max_length=50, verbose_name='最小薪资'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='mix_salary',
            field=models.FloatField(default=0, max_length=50, verbose_name='最小薪资'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='职位名称'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='work_area',
            field=models.CharField(default='北京', max_length=50, verbose_name='工作地点'),
        ),
    ]
