# Generated by Django 3.1.2 on 2020-11-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0005_auto_20201101_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='education',
            field=models.CharField(choices=[('不限', '不限'), ('高中', '高中'), ('大专', '大专'), ('本科', '本科'), ('硕士', '硕士'), ('硕士', '博士')], default='', max_length=10, verbose_name='学历'),
        ),
    ]
