# Generated by Django 3.1.2 on 2021-01-31 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0006_auto_20201102_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='company_type',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='company_size',
            field=models.CharField(default='', max_length=20, verbose_name='公司人数'),
        ),
    ]
